### PR TITLE
Merge CuteDSCapture

### LINKED ISSUE #4: Combine CuteDSCapture and Cute3DSCapture into one tool
Just putting this here to remember.

This does not mean I'll do this in the short term, but if I ever get around to working on CuteCapture again, this would be one of the things I want to do.

### PR DESCRIPTION
**Pull request by Gotos**
Right now, CuteDSCapture is even less maintained than Cute3DSCapture. As they share a lot of their codebase anyway, I want to merge them into one. Thus, this Pull Request.

I could use some feedback on this. Right now, their are a few problems, not all of which are how the tools run:

1) CDC runs slow. This is because of the framerate limiter. The limiter is set to 60 FPS, but apparently this slows the capturing down. I couldn't get CDC running faster than 45-50 FPS - until I commented the framerate limiting out. Which is not desirable, it was added because people complained about C3C hogging resources when not connected to a 3DS. I.e., when not connected and not framerate limited, C3C (and CDC) run at thousands of FPS and can block an entire core.
The solution would probably be to limit how often CuteCapture checks if the console was reconnected and then get rid of the framerate limiter - we'd essentially how our own that way.

2) The code is really a mess. If already was before this Pull Request, but it's worse now. There are `ifdef`s all over the place and even worse - there are `ifndef`s checking for the same macro mixed in as well. One letter, big implications. This probably needs a bigger refactoring, which is most likely worth it's own pull request. Also, those refactorings might break the audio capturing code that is being developed. Need to clarify that as well.

3) Having an IDE that only somewhat understands my code doesn't really help with the clean-up. I might want to change from autotools to cmake so CLion can understand the project (and because I much prefer cmake by now), but that's another big change. If we want to get a CI/CD pipeline for building these tools up and running, these changes should be clarified in advance. Might be worthy of another Pull Request as well.

Any thoughts on any of these? I'd tend to move all three points into separate issues/pull requests, but point 1 is actually a regression, looking from a users perspective. Not sure if I feel happy about releasing something that is, for the user, objectively worse than the previous version.

### CODE REVIEW

**Comment by Gotos** [comment]
@sudofox and @vgmoose, you've both worked on this project before - can I get some comments on this pull request from you? :)

**Comment by sudofox** [comment]
Hey, I'll take a look when I get a sec! I'm out of state right now for a while so I hadn't checked GitHub in a bit.

That said, I don't have a DS capture unit (though I do have my 3DS) so actual testing may be a bit one-sided.

**Comment by Gotos** [comment]
No worries, take your time!
I'm mostly interested in thoughts to the open questions in the description of the PR; so far I'm hopeful that this is still small enough that I can easily test it on my own, so having no DS shouldn't be much of a problem :)

**Comment by sudofox** [comment]
I'd like to apologize - I simply haven't had the time to really review this. I think that you might work on those things you mentioned before officially merging it in - I don't think it's bothering anyone to have two different applications. Might end up with a No$GBA-esque situation where the name of the application doesn't really match everything that it does anymore :D but hey

I think the work you've done so far has been absolutely fantastic. You're pretty cool!

I was wondering if you have Discord or something, by the way, it'd be nice to chat outside of GitHub comments.

**Comment by vgmoose** [comment]
I don't have any objections to merging them in, the code looks good to me, and if it reduces overall management that seems like a win!

This approach is simpler, as it still produces two separate apps, but I could also see an argument to allowing both of them to work at the same time (and splitting the logic after detection with regular if statements rather than compiler-level) and then having a single app. I'm not sure on the technical feasibility of that (detection + usability) however.

As far as the IFDEFs go, I've seen them used in other projects in way harder to read / more spread out scenarios, so if that's all it really takes to get C3C and CDC sharing a source code that's pretty impressive!

Would a workaround for frame limiting regression to be to disable it for now in CDC code only?

Also regarding CI, I think these merges should still work with #8 for C3C, and should be extendable to CDC as well.

**Comment by Gotos** [comment]
Thanks for the feedback and sorry for taking a while to get back to this.

I'll try to have a look at this again at the weekend and see if there are easy wins regarding runtime detection and framerate limiting. Thanks again! :)

**Comment by Gotos** [comment]
> I was wondering if you have Discord or something, by the way, it'd be nice to chat outside of GitHub comments.

Sorry, I only just saw this part of your message. I do have Discord, yes, I'll drop you my contact in a Twitter DM (seeing you've got your Twitter linked in your profile) :)

**Comment by GimmyTomas** [comment]
Hi @Gotos and thank you for your work!

I am not a programmer and I have limited knowledge of C++. However, I am trying to edit the CDC code to fix a couple of issues. One of them is point 1 of your message above.

Can you please point out where the framerate limiter is? I was not able to locate it in the CDC code.

By "limiting how often CDC checks is the DS was reconnected" you mean something like: put some waiting time here?
`if(!init) {
            init = dscapture_init();
        }`

I am using CDC on Mac and, when using other programs such as OBS, CDC loses lines very often, such as in the image attached. I honestly would be happy to make CDC ignore half the frames (so, getting a 30fps output) if this helps removing the issue.

EDIT: oddly enough, I noticed that the occurrence CDC losing lines depends on the size of the window. The bigger the window, the higher the rate of graphical "glitches".

Schermata 2020-10-29 alle 12 55 23

**Comment by Gotos** [comment]
> By "limiting how often CDC checks is the DS was reconnected" you mean something like: put some waiting time here?
if(!init) { init = dscapture_init(); }

Yes, basically.

The framerate limiter is handled by `window.setFramerateLimit(60);` in the main.cpp.

Although both of these only apply to this branch, not the current main CDC repo - right now, the released versions of CDC don't have framerate limiting.

Not sure what causes those line glitches, but I'm pretty sure it's not related to the changes in this MR. Can you confirm which version of CDC you are using? The standalone one from https://github.com/Gotos/CuteDSCapture/ or the one from this branch?

**Comment by GimmyTomas** [comment]
Hi, thanks for the reply! I am using the standalone one from https://github.com/Gotos/CuteDSCapture/, that's why I didn't find the framerate limiter.

I'll have a look at the changes you made in the branch here and see if they help!

**Comment by Gotos** [comment]
The newest commit removes the frame limiter and introduces a non-blocking wait until the device is connected. I don't think I'll do the overall cleanup in this branch, so I'll merge it soon.

**Review by sudofox — APPROVED** [review]

**Pull request merged**
